### ISSUE TITLE
bpf permission denied

### ISSUE THREAD

**Issue by wenzt** [AliyunContainerService/terway-qos#14]
Hi,
I am trying terway-qos with image version  registry.cn-hangzhou.aliyuncs.com/acs/terway-qos:v0.2.0
host kernel version: 4.19.9

I got two issues:
1. 
`E1201 07:22:05.538273       1 mamager.go:52] bpf "msg"="mkdir failed" "error"="mkdir /sys/fs/bpf/terway: no such file or directory"`
Initcontainer mount bpf filesystem success on /sys/fs/bpf, but in terway-qos container bpf not mounted.  I think is because initcontainer and terway-qos belong to two different mount namespace? 

2. terway-qos contaienr stop running and logs is:
```
I1201 08:12:11.893097     122 damon.go:65] version: qos/v0.1.0 (linux/amd64) deaa8fbc6d9062d07206c0e9488a53efd48693a6 2023-11-13T09:39:04Z
I1201 08:12:11.895064     122 compile.go:56] bpf "msg"="exec" "cmd"="/usr/bin/clang -g -O2 -target bpf -std=gnu99 -I/var/lib/terway/headers -c /var/lib/terway/src/qos_tc.c -o /var/lib/terway/qos_tc.o"
E1201 08:12:12.912234     122 mamager.go:98] bpf "msg"="load bpf objects failed" "error"="field QosCgroup: program qos_cgroup: load program: permission denied: 48: (61) r1 = *(u32 *)(r7 +160): invalid bpf_context access off=160 size=4 (31 line(s) omitted)"
```
what versions that terway-qos supported? and how to fix this issue?

**Comment by l1b0k** [comment]
Have you deploy via the charts in the project ? 
The bpf fs is mounted is the deploy .
Current we used this with kernel 5.10 . Kernel 4.19 haven't tested yet .

**Comment by wenzt** [comment]
@l1b0k Thank you for replying.
Got you. Initcontainer using init.sh enter host namespace then mount bpf file system.
I tested with kernel 5.4,  host lost network connection after terway-qos pod running.

**Comment by l1b0k** [comment]
Could you provied more detail about the issue ?
- dmesg
- enter terway-qos . execute `qos bandwidth list`
